# Generated by Django 3.0.8 on 2020-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
